const LandlordBreadcrums = {
  "/landlord": "Home",
  "/landlord/dashboard": "Home",
  "/landlord/settings": "Settings",
  "/landlord/settings/info": "Profile Info",
  "/landlord/settings/social-connect": "Social Connect",
  "/landlord/settings/payment-method": "Payment Method",
  "/landlord/settings/persona": "Persona Profile",
  "/landlord/settings/accountsetting": "Account Setting",
  "/landlord/settings/privacy": "Privacy",
  "/landlord/settings/security": "Security",
  "/landlord/settings/subscriptions": "Subscriptions",
  "/landlord/settings/notifications": "Notifications",
  "/landlord/settings/userRole": "User Role",
  "/landlord/settings/chartOfAccount": "Chart Of Account",
  "/landlord/screening": "Screening",
  "/landlord/screening/review": "Review",
  "/landlord/screening/order": "New Order",
  "/landlord/screening/report": "Report",
  "/landlord/fixit": "Fix It",
  "/landlord/fixit/task": "Task",
  "/landlord/fixit/task/review": "Review",
  "/landlord/fixit/task/offers": "Offers",
  "/landlord/fixit/raisetask": "Raise Task",
  "/landlord/fixit/update": "Update Task",
  "/landlord/property": "Properties",
  "/landlord/property/edit": "Update Property",
  "/landlord/listings": "Listings",
  "/landlord/listings/add": "Add Listings",
  "/landlord/property/listing": "Listing",
  "/landlord/property/listing/edit": "Update Listing",
  "/landlord/listing/preview": "Preview Listing",
  "/landlord/property/add": "Add Property",
  "/landlord/accounting": "Accounting",
  "/landlord/accounting/rental-invoice": "Rental Invoice",
  "/landlord/accounting/rental-transaction": "Transaction",
  "/landlord/accounting/rental-deposits": "Deposits",
  "/landlord/calendar": "Calendar",
  "/landlord/messenger": "Messenger",
  "/landlord/property/review": "View Listing",
  "/landlord/documents/addNew": "Add New Document",
  "/landlord/agreement": "Agreement",
  "/landlord/documents": "Documents",
  "/landlord/inventory": "Inventory",
  "/landlord/inventory/add": "Add New Inventory",
  "/landlord/inventory/edit": "Edit Inventory Data",
  "/landlord/contacts": "Contacts",
  "/landlord/applications": "Applications",
  "/landlord/reports": "Reports",
  "/landlord/agreement/add": "Add New Agreement",
  "/landlord/agreement/edit": "Edit Agreement Data",
  "/landlord/service-orders": "Service Orders",
  "/landlord/book-viewing": "Viewing Request",
  "/landlord/mandates": "Manage Mandates",
  "/landlord/recurring-invoice/": "Recurring Invoice",
};

export default LandlordBreadcrums;
