const RenterBreadcrums = {
  "/renter": "Home",
  "/renter/dashbaord": "Home",
  "/renter/manage-rent": "Manage Rent",
  "/renter/manage-deposit": "Manage Deposit",
  "/renter/settings": "Settings",
  "/renter/settings/info": "Profile Info",
  "/renter/settings/social-connect": "Social Connect",
  "/renter/settings/payment-method": "Payment Method",
  "/renter/settings/persona": "Persona Profile",
  "/renter/settings/accountsetting": "Account Setting",
  "/renter/settings/privacy": "Privacy",
  "/renter/settings/security": "Security",
  "/renter/settings/subscriptions": "Subscriptions",
  "/renter/settings/notifications": "Notifications",
  "/renter/settings/userRole": "User Role",
  "/renter/screening": "Screening",
  "/renter/screening/review": "Review",
  "/renter/screening/order": "New Order",
  "/renter/fixit": "Fix It",
  "/renter/fixit/raisetask": "Raise Task",
  "/renter/calendar": "Calendar",
  "/renter/messenger": "Messenger",
  "/renter/wishlist": "Rental Wishlist",
  "/renter/fixit/task/offers": "Task",
  "/renter/myrental": "My Rental",
  "/renter/myrental/add": "Add New",
  "/renter/contacts": "Contacts",
  "/renter/service-orders": "Service Orders",
  "/renter/mandates": "Manage Mandates",
  "/renter/recurring-invoice/": "Recurring Invoice",
};

export default RenterBreadcrums;
